// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMLmQl1l1ZuyCtwEv-YjJLR_ihQYBzmvs',
    appId: '1:856543010937:web:0571b661539554e53cb4a8',
    messagingSenderId: '856543010937',
    projectId: 'ai-weather-7dbb3',
    authDomain: 'ai-weather-7dbb3.firebaseapp.com',
    storageBucket: 'ai-weather-7dbb3.firebasestorage.app',
    measurementId: 'G-FNXG8T55Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp8Dj-AMCouqt9Pw2-U8AG5GmFtSFYMYo',
    appId: '1:856543010937:android:dc68a1d29b5388bc3cb4a8',
    messagingSenderId: '856543010937',
    projectId: 'ai-weather-7dbb3',
    storageBucket: 'ai-weather-7dbb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdpW66fB1nBJYUBruseQ9QsNjgAn3EGvY',
    appId: '1:856543010937:ios:db9d2f39bd3dbf523cb4a8',
    messagingSenderId: '856543010937',
    projectId: 'ai-weather-7dbb3',
    storageBucket: 'ai-weather-7dbb3.firebasestorage.app',
    iosBundleId: 'com.example.aiWeather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdpW66fB1nBJYUBruseQ9QsNjgAn3EGvY',
    appId: '1:856543010937:ios:db9d2f39bd3dbf523cb4a8',
    messagingSenderId: '856543010937',
    projectId: 'ai-weather-7dbb3',
    storageBucket: 'ai-weather-7dbb3.firebasestorage.app',
    iosBundleId: 'com.example.aiWeather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMLmQl1l1ZuyCtwEv-YjJLR_ihQYBzmvs',
    appId: '1:856543010937:web:d8fded9faefe82973cb4a8',
    messagingSenderId: '856543010937',
    projectId: 'ai-weather-7dbb3',
    authDomain: 'ai-weather-7dbb3.firebaseapp.com',
    storageBucket: 'ai-weather-7dbb3.firebasestorage.app',
    measurementId: 'G-C8WQ8GLZ7E',
  );

}